### ISSUE TITLE
New Types of Sources

### ISSUE THREAD

**Issue by yujunwoo** [briankavanaugh/APA-7th-Edition#13]
Hello, great day ahead to the team and to you! I am really thankful for this upgrade.

May I ask the creators and editors of the code if they can **add "Legislations", "Constitutions", "Codes", and "Executive Issuances"** as _new_ **types of source**? We cite laws and legislations every now and then: however, the sources I mentioned were not included, therefore automation of the citation and bibliographic entry is not present.

The guidelines are in this link: https://www.legalbluebook.com/bluebook/v21/tables/t2-foreign-jurisdictions/t2-33-philippines#:~:text=Citation%20format%3A%20%3Cstatute%20name%20or,not%20evident%20from%20context%3E).

Thank you very much!

**Comment by briankavanaugh** [comment]
Again, I am not the creator of this. I'm providing this as a service. If I understand you correctly, what you're asking for is in the interface for Word and has nothing to do with this file, anyway.

You want something added here, right?

![image](https://github.com/briankavanaugh/APA-7th-Edition/assets/13356729/ca71fba0-11c7-44aa-8ece-66a075cbaeef)

**Comment by briankavanaugh** [comment]
I do not see a list of sources in the xsl file. I see a lot of places where the selection is tested for, so updating it for additional sources would be a lot of work. However, I don't see anywhere where the list of options itself is defined.
