### ISSUE TITLE
URL & DOI displayed as text, instead of hyperlinks

### ISSUE THREAD

**Issue by atilagbs** [briankavanaugh/APA-7th-Edition#8]
First of all, great f*ing job, you guys! I've had a hard time finding a template that works for me and this is goddamn it!
And it's also amazing that this is on Github, so it can be continuously improved. I'm so happy I could cry — and maybe I did a little bit.

The only thing I'm missing though is the URL and DOI not being blue colored and underlined, as usual APA 7th hyperlinks.
I've tried fixing it by myself so I could share it here, but I pretty much sucked at messing with the XSL coding. So... help?

Bellow I've attached the problem ilustrated.

![image](https://user-images.githubusercontent.com/52422849/191413308-b805a698-da96-49b9-91cc-61897c87a844.png)

**Comment by briankavanaugh** [comment]
Recent PR added support for this
